version: "3.7"

services:

  communication-api-test:
    environment:
      - rabbitMQ__Url=rabbitmq://rabbitmq
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=${COMMON_TESTRESULTSDIRECTORY}/communication-api-test/test-results.trx
      - /p:CollectCoverage=true
      - /p:CoverletOutputFormat=opencover
      - /p:CoverletOutput=${COMMON_TESTRESULTSDIRECTORY}/communication-api-test/coverage/
      - --no-restore

  contact-api-test:
    environment:
      - rabbitMQ__Url=rabbitmq://rabbitmq
      - ConnectionStrings__default=Server=postgresql;Port=5432;Database=crm-contact-test;User Id=lab;Password=P@ssw0rd;
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=${COMMON_TESTRESULTSDIRECTORY}/contact-api-test/test-results.trx
      - /p:CollectCoverage=true
      - /p:CoverletOutputFormat=opencover
      - /p:CoverletOutput=${COMMON_TESTRESULTSDIRECTORY}/contact-api-test/coverage/
      - --no-restore
