version: '3.7'

services:
  vault:
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=secret

  seq:
    ports:
      - "5341:5341"
      - 5340:80

  jaeger:
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
    ports:
      - 3000:3000

  # influxdb:
  #   ports:
  #     - 8086:8086
  #     - 8083:8083

  prometheus:
    ports:
      - 9090:9090

  postgresql:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=lab
      - POSTGRES_PASSWORD=P@ssw0rd

  rabbitmq:
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  contact-api:
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - Jaeger__Enabled=true
      - Jaeger__UdpHost=jaeger
      - ConnectionStrings__contact=Server=postgresql;Port=5432;Database=crm-contact;User Id=lab;Password=P@ssw0rd;
      - rabbitMQ__Url=rabbitmq://rabbitmq
      - Logging__Seq__Url=http://seq/
      - metrics__enabled=true
      - metrics__prometheusEnabled=true
      - metrics__influxEnabled=false

  contact-migration:
    environment:
      - ConnectionStrings__contact=Server=postgresql;Port=5432;Database=crm-contact;User Id=lab;Password=P@ssw0rd;
    entrypoint:
      - dotnet
      - CRM.Migration.dll
      - contact

  identity-api:
    ports:
      - 5101:80
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - PathBase=/identity
      - Jaeger__Enabled=true
      - Jaeger__UdpHost=jaeger
      - ConnectionStrings__identity=Server=postgresql;Port=5432;Database=crm-identity;User Id=lab;Password=P@ssw0rd;
      - Logging__Seq__Url=http://seq/
      - metrics__enabled=true
      - metrics__prometheusEnabled=true
      - metrics__influxEnabled=false

  identity-migration:
    environment:
      - ConnectionStrings__identity=Server=postgresql;Port=5432;Database=crm-identity;User Id=lab;Password=P@ssw0rd;
    entrypoint:
      - dotnet
      - CRM.Migration.dll
      - identity

  communication-api:
    ports:
      - 5002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - Jaeger__UdpHost=jaeger
      - Jaeger__Enabled=true
      - rabbitMQ__Url=rabbitmq://rabbitmq
      - Logging__Seq__Url=http://seq/
      - metrics__enabled=true
      - metrics__prometheusEnabled=true
      - metrics__influxEnabled=false

  crm-web:
    ports:
      - 5102:80
    environment:
      - IDENTITY_WEB_HOST=localhost:5101

  graph-gateway:
    ports:
      - 5100:80
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - Jaeger__UdpHost=jaeger
      - Services__ContactService__Url=http://contact-api
      - Jaeger__Enabled=true
      - Cors__Origins=http://localhost:5102
      - Logging__Seq__Url=http://seq/
      - metrics__enabled=true
      - metrics__prometheusEnabled=true
      - metrics__influxEnabled=false
