version: '3.7'

services:
  vault:
    image: vault
    container_name: vault
    networks:
      - crm
    cap_add:
      - IPC_LOCK

  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    networks:
      - crm
    volumes:
      - seq-data:/data

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    networks:
      - crm

  postgresql:
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - crm

  keycloak:
    image: jboss/keycloak:6.0.1
    container_name: keycloak
    networks:
      - crm
    depends_on:
      - postgresql

  nats:
    image: nats
    container_name: nats
    networks:
      - crm

  contact-migration:
    image: ${REGISTRY:-crmnow}/contact-migration:${TAG:-latest}
    build:
      context: .
      dockerfile: src/BuildingBlocks/CRM.Migration/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    volumes:
      - ./src/BuildingBlocks/CRM.Migration/Scripts/:/app/Scripts:ro
    networks:
      - crm
    depends_on:
      - postgresql

  contact-api:
    image: ${REGISTRY:-crmnow}/contact-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Contact/CRM.Contact/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    networks:
      - crm
    depends_on:
      - postgresql
      - nats
      - jaeger

  identity-migration:
    image: ${REGISTRY:-crmnow}/identity-migration:${TAG:-latest}
    build:
      context: .
      dockerfile: src/BuildingBlocks/CRM.Migration/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    volumes:
      - ./src/BuildingBlocks/CRM.Migration/Scripts/:/app/Scripts:ro
    networks:
      - crm
    depends_on:
      - postgresql

  identity-api:
    image: ${REGISTRY:-crmnow}/identity-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Identity/CRM.Identity/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    networks:
      - crm
    depends_on:
      - postgresql
      - nats
      - jaeger

  communication-api:
    image: ${REGISTRY:-crmnow}/communication-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Communication/CRM.Communication/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    networks:
      - crm
    depends_on:
      - nats

  graph-gateway:
    image: ${REGISTRY:-crmnow}/graph-gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Gateways/CRM.Graph.Gateway/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    networks:
      - crm
    depends_on:
      - contact-api
      - communication-api

volumes:
  postgres-data:
  nexus-data:
  seq-data:

networks:
  crm:
    name: crm-network
