version: '3.7'

services:
  vault:    
    ports: 
      - 8200:8200
    environment: 
      - VAULT_DEV_ROOT_TOKEN_ID=secret

  seq:
    ports: 
      - "5341:5341"

  jaeger:
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

  postgresql:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=lab
      - POSTGRES_PASSWORD=P@ssw0rd

  keycloak:
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=lab
      - KEYCLOAK_PASSWORD=P@ssw0rd
      - DB_ADDR=postgresql
      - DB_USER=lab
      - DB_PASSWORD=P@ssw0rd
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
  
  nats:
    ports: 
      - 4222:4222
      - 6222:6222
      - 8222:8222

  contact-api:
    ports:
      - 5000:80
    environment: 
      - ConnectionStrings__default=Server=postgres.data;Port=5432;Database=crm-contact;User Id=lab;Password=P@ssw0rd;
  
  contact-api-migration:
    environment: 
      - ConnectionStrings__contact=Server=postgres.data;Port=5432;Database=crm-contact;User Id=lab;Password=P@ssw0rd;
    entrypoint:      
      - dotnet
      - run
      - contact

      
  lead-migration:
    environment:
      - ConnectionStrings__lead=Server=postgresql;Port=5432;Database=crm-lead;User Id=lab;Password=P@ssw0rd;
    entrypoint:
      - dotnet
      - CRM.Migration.dll
      - lead


  lead-api:
    ports:
      - 5001:80
    environment: 
      - NATS__Url=http://nats:4222
      - Jaeger__UdpHost=jaeger
      - ConnectionStrings__default=Server=postgresql;Port=5432;Database=crm-lead;User Id=lab;Password=P@ssw0rd;

  communication-api:
    ports:
      - 5002:80
    environment: 
      - NATS__Url=http://nats:4222
      - Jaeger__UdpHost=jaeger

  graph-gateway:
    ports:
      - 5100:80
    environment: 
      - Jaeger__UdpHost=jaeger
      - Services__LeadService__Url=http://lead-api
