version: '3.7'

services:
  vault:
    image: vault
    container_name: vault
    networks:
      - crm
    cap_add:
      - IPC_LOCK

  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    networks:
      - crm
    volumes:
      - seq-data:/data
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - crm

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    networks:
      - crm

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - crm
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - crm
    volumes:
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  postgresql:
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - crm

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - crm

  contact-migration:
    image: ${REGISTRY:-crmnow}/contact-migration:${TAG:-latest}
    build:
      context: .
      dockerfile: src/BuildingBlocks/CRM.Migration/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    volumes:
      - ./src/BuildingBlocks/CRM.Migration/Scripts/:/app/Scripts:ro
    networks:
      - crm
    depends_on:
      - postgresql

  contact-api:
    image: ${REGISTRY:-crmnow}/contact-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Contact/CRM.Contact.Api/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    networks:
      - crm
    depends_on:
      - postgresql
      - rabbitmq
      - jaeger

  identity-migration:
    image: ${REGISTRY:-crmnow}/identity-migration:${TAG:-latest}
    build:
      context: .
      dockerfile: src/BuildingBlocks/CRM.Migration/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    volumes:
      - ./src/BuildingBlocks/CRM.Migration/Scripts/:/app/Scripts:ro
    networks:
      - crm
    depends_on:
      - postgresql

  identity-api:
    image: ${REGISTRY:-crmnow}/identity-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Identity/CRM.Identity/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    networks:
      - crm
    depends_on:
      - postgresql
      - jaeger

  communication-api:
    image: ${REGISTRY:-crmnow}/communication-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Communication/CRM.Communication.Api/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    networks:
      - crm
    depends_on:
      - rabbitmq
      - jaeger

  crm-web:
    image: ${REGISTRY:-crmnow}/crm-web:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/CRM.Portal.Web/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    networks:
      - crm
    depends_on:
      - graph-gateway
      - identity-api

  graph-gateway:
    image: ${REGISTRY:-crmnow}/graph-gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Gateways/CRM.Graph.Gateway/Dockerfile
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    networks:
      - crm
    depends_on:
      - contact-api
      - communication-api
      - identity-api

volumes:
  postgres-data:
  seq-data:
  grafana:
  prometheus:

networks:
  crm:
    name: crm-network
