variables:
    crm.registryendpoint: crm-registry
    disable.coverage.autogenerate: 'true'
    crm.azuresubscription: AKS-lab-01
    crm.azureresourcegroup: lab
    crm.kubernetescluster: aks-lab-01

trigger:
  branches:
    include:
      - master
      - feature/*
    exclude:
      - ref/tags/*
  paths:
    include:
      - src/Communication/CRM.Communication.Api
      - src/Communication/CRM.Communication.FunctionalTests
      - src/BuildingBlocks/CRM.DataContract
      - src/BuildingBlocks/CRM.Shared

stages:

- stage: Pre_Build
  displayName: Pre build
  jobs:
    - template: ../pre-build.yml

- stage: Build_Run_Integration_Tests
  displayName: Build and run integration tests
  dependsOn: Pre_Build
  jobs:
    - template: ../prepare-env.yml
    
    - template: ../build-services.yml
      parameters:
        services: communication-api

    - template: ../run-integration-test.yml
      parameters:
        testService: communication-api-test

- stage: Publish_Docker_Images
  displayName: Docker images
  dependsOn: Build_Run_Integration_Tests
  condition: and(succeeded(), eq(variables['crm.nightlybuild'], 'true'))
  jobs:
    - template: ../prepare-env.yml

    - template: ../publish-docker-images.yml
      parameters:
        services: communication-api
        registryEndpoint: $(crm.registryendpoint)

- stage: Publish_Helm_Chart
  displayName: Publish helm chart
  dependsOn: Publish_Docker_Images
  condition: and(succeeded(), eq(variables['CRM.NightlyBuild'], 'true'))
  jobs:
    - template: ../prepare-env.yml

    - template: ../publish-helm-chart.yml
      parameters:
        service: communication-api
        azuresubscription: $(CRM.azuresubscription)
        azureresourcegroup: $(CRM.azureresourcegroup)
        kubernetescluster: $(CRM.kubernetescluster)

- stage: Deploy_Dev_Environment
  displayName: Deploy on Dev environment
  dependsOn: Publish_Helm_Chart
  jobs:
    - template: ../prepare-env.yml

    - template: ../install-helm-chart.yml
      parameters:
        service: communication-api
        azuresubscription: $(CRM.azuresubscription)
        azureresourcegroup: $(CRM.azureresourcegroup)
        kubernetescluster: $(CRM.kubernetescluster)
        kubernetesnamespace: dev
